#!/bin/bash
# daemonlogger Init Script

DAEMONLOGGER_BIN=/usr/bin/daemonlogger
INITAL_DAEMONLOGGER_RENAME_SCRIPT=/opt/ids_scripts/utils/daemonlogger_ls_rename.sh
DAEMONLOGGER_RENAME_DAEMON_SCRIPT=/opt/ids_scripts/utils/daemonlogger_inotify_rename.sh
PCAP_LOCATION=/packet_recorder/.pcap
RENAMED_PCAP_LOCATION=/packet_recorder

# Kill off any other daemonlogger processes using pkill
echo "Stopping old daemonlogger instances, and renamer scripts"
pkill -f $DAEMONLOGGER_BIN
pkill -f $INITAL_DAEMONLOGGER_RENAME_SCRIPT
pkill -f $DAEMONLOGGER_RENAME_DAEMON_SCRIPT

sleep 1

# Renaming existing daemonlogger generated pcaps
$INITAL_DAEMONLOGGER_RENAME_SCRIPT $PCAP_LOCATION $RENAMED_PCAP_LOCATION

# Starting script to rename new files that are created and backgrounds it
$DAEMONLOGGER_RENAME_DAEMON_SCRIPT $PCAP_LOCATION $RENAMED_PCAP_LOCATION &

# Start Daemonloggers #
echo "Launching daemonlogger(s).."
#Starts daemonloggert as a daemon  ------ interface --location--- % of free space --filename -- ring mmmkkkbbb 

echo ""

sleep 1

# done, verify they launched
PIDS=$(pgrep -f $DAEMONLOGGER_BIN)
PID_COUNT=${#PIDS[@]}
if [ $PID_COUNT -gt 0 ]
then
	echo "Daemonlogger processes are running "
else
	echo "No daemonloggers were started. Possible errors."
fi