#!/bin/bash
# Written by Dan Jones, 2015-04
# # Script to rename new pcaps generated by daemonlogger, inspired by Nathan Fowler's daemonlogger renamer script.

#Test for arguments, fail if they aren't supplied
if ! [ $2 ]; then
	echo "Usage is ${basename} [pcap_dir] [renamed_pcap_dir]"
	exit 1
fi

#Variables
PCAP_DIR=$1
RENAMED_PCAP_DIR=$2

echo "Creating renamed symlinks for pcaps in ${PCAP_DIR} in ${RENAMED_PCAP_DIR}"

#Purge all of the old symlinks that refence an invalid file before creating new links
find $RENAMED_PCAP_DIR -follow -type l -delete

PCAP_FILES=$(ls $PCAP_DIR)
#echo $PCAP_FILES
for PCAP in $PCAP_FILES
do
	PCAP_TITLE=$(echo $PCAP | awk -F"." '{print $1}')
	EPOCH_VALUE=$(echo $PCAP | awk -F"." '{print $2}') 
	#echo $EPOCH_VALUE
	HUMAN_DATE=$(date -d @$EPOCH_VALUE +"%Y-%m-%d_%T")
	#echo $HUMAN_DATE
	ln -s $PCAP_DIR/$PCAP $RENAMED_PCAP_DIR/$PCAP_TITLE.$HUMAN_DATE
done