#!/bin/bash
# Written by Dan Jones, 2015-04
# Script to rename new pcaps generated by daemonlogger, inspired by Nathan Fowler's daemonlogger renamer script.

# inotify-tools must be installed for this script to work

#Test for arguments, fail if they aren't supplied
if ! [ $2 ]; then
	echo "Usage is ${basename} [pcap_dir] [renamed_pcap_dir]"
	exit 1
fi

PCAP_DIR=$1
RENAMED_PCAP_DIR=$2

echo "Watching for pcaps in ${PCAP_DIR} and creating renamed symlinks in ${RENAMED_PCAP_DIR}"

inotifywait -m -e create --format "%f" $PCAP_DIR | while read PCAP
do
	#Purge all of the old symlinks that refence an invalid file before creating new links
	find -L $RENAMED_PCAP_DIR -type l -delete 
	
	#Renames new files and creates a human readable symlink
	PCAP_TITLE=$(echo $PCAP | awk -F"." '{print $1}')
	EPOCH_VALUE=$(echo $PCAP | awk -F"." '{print $2}') 
	#echo $EPOCH_VALUE
	HUMAN_DATE=$(date -d @$EPOCH_VALUE +"%Y-%m-%d_%T")
	#echo $HUMAN_DATE
	ln -s $PCAP_DIR/$PCAP $RENAMED_PCAP_DIR/$PCAP_TITLE.$HUMAN_DATE
done